<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<nav>
<div>
	<div>&nbsp;공지사항&nbsp;</div>
	|
	<div>&nbsp;HTML&nbsp;</div>
	|
	<div>&nbsp;CSS&nbsp;</div>
	|
	<div>&nbsp;JS&nbsp;</div>
	|
	<div>&nbsp;JAVA&nbsp;</div>
	|
	<div>&nbsp;JSP&nbsp;</div>
	|	
	<div>&nbsp;DB&nbsp;</div>
	|
	<div>&nbsp;QnA&nbsp;</div>
</div>
</nav>