<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<nav>
<div>
	<div>&nbsp;<span>공지사항</span>&nbsp;</div>
	|
	<div>&nbsp;<span>HTML</span>&nbsp;</div>
	|
	<div>&nbsp;<span>CSS</span>&nbsp;</div>
	|
	<div>&nbsp;<span>JS</span>&nbsp;</div>
	|
	<div>&nbsp;<span>JAVA</span>&nbsp;</div>
	|
	<div>&nbsp;<span>JSP</span>&nbsp;</div>
	|	
	<div>&nbsp;<span>DB</span>&nbsp;</div>
	|
	<div>&nbsp;<span>QnA</span>&nbsp;</div>
</div>
</nav>